/* Angels Network — translations (PT · EN · DE · FR). Place names kept untranslated. */
window.T = {
pt:{
 nav_people:"As pessoas",nav_opps:"Oportunidades",nav_match:"Match",nav_move:"Mudar-se",nav_how:"Como funciona",nav_cta:"Quero ajudar",
 hero_eyebrow:"Baixo Alentejo &amp; Algarve",
 hero_h1:"Encontre quem precisa de si.<br><span class='hl'>Em minutos.</span>",
 hero_lead:"A plataforma que liga voluntários a pessoas idosas que vivem sós, no sul de Portugal. Explore o quadro, conheça as pessoas, ou deixe o match inteligente encontrar a ligação certa.",
 hero_cta1:"Encontrar o meu match",hero_cta2:"Ver oportunidades",
 trust1:"Gratuito",trust2:"Voluntários verificados",trust3:"1h por semana já chega",
 mock_search:"Procurar perto de si…",mock_c1_t:"Tardes de conversa · Beja",mock_c1_m:"Terças · 15:00",mock_c2_t:"Boleia ao médico · Serpa",mock_c2_m:"Quinta · 9:30",
 mock_ai_b:"Match inteligente",mock_ai_s:"3 ligações perfeitas para si",mock_float_s:"quer companhia · Beja",
 strip_partner:"Em parceria com",
 match_eyebrow:"Match inteligente",match_h2:"Diga-nos como gostaria de ajudar. Encontramos quem precisa de si.",
 match_sub:"Responda a três perguntas e cruzamos zona, disponibilidade e o que gosta de fazer com quem precisa de companhia perto de si.",
 match_q1:"1 · Onde está?",match_q2:"2 · Quando tem tempo?",match_q3:"3 · O que gosta de fazer?",
 z_remoto:"À distância",z_any:"Indiferente",q_manha:"Manhãs",q_tarde:"Tardes",q_fds:"Fins de semana",q_flex:"Flexível",
 g_companhia:"Conversar",g_boleia:"Conduzir",g_evento:"Animar convívios",g_apoio:"Ajudar nas tarefas",g_admin:"Bastidores",
 match_btn:"Encontrar o meu match",match_note:"Pesquisa inteligente · em breve com IA conversacional",
 why_pre:"Combina com",why_zone:"a sua zona",why_like:"o que gosta",why_avail:"a sua disponibilidade",why_def:"Uma boa primeira oportunidade",
 people_eyebrow:"As pessoas",people_h2:"Conheça quem espera por si",
 people_lead:"Não são tarefas — são pessoas. Veja quem vive só, conheça as suas necessidades, e escolha como quer ajudar.",
 pf_all:"Tudo",pf_want:"Querem companhia",pf_ride:"Precisam de boleia",
 people_note:"Perfis partilhados com consentimento e protegidos — os dados completos só ficam visíveis após a sua verificação.",
 plink:"Ver o que precisa →",angel_one:"1 Anjo já ajuda",angel_many:"%n Anjos já ajudam",angel_none:"Ainda sem Anjo",
 board_eyebrow:"Ou por tarefa",board_h2:"O quadro de oportunidades",board_lead:"Cada cartão é uma tarde na vida de alguém. Filtre por causa, zona ou disponibilidade.",
 f_remoto:"À distância",count_word:"oportunidades",tag_vet:"Requer verificação",spot_one:"vaga",spot_many:"vagas",filled:"Preenchida",
 c_companhia:"Companhia",c_boleia:"Boleia",c_evento:"Convívio",c_apoio:"Apoio",c_admin:"Bastidores",
 cad_weekly:"Toda a semana",cad_fortnightly:"Quinzenal",cad_one_morning:"Uma manhã",cad_your_pace:"Ao seu ritmo",
 d_tue:"Terças",d_thu:"Quinta",d_sat:"Sábado",d_wed:"Quartas",d_fri:"Sextas",d_flex:"Flexível",
 how_eyebrow:"Simples",how_h2:"Como funciona",
 step1_t:"1 · Escolha",step1_p:"Encontre uma oportunidade ou pessoa no quadro, ou deixe o match sugerir a ligação certa.",
 step2_t:"2 · Conheça",step2_p:"Falamos consigo, fazemos uma verificação simples e apresentamo-lo à pessoa — só avança com o seu sim.",
 step3_t:"3 · Apareça",step3_p:"Vai à hora combinada, faz companhia e regista a visita. Uma hora por semana muda tudo.",
 reloc_eyebrow:"Venha viver e ajudar",reloc_h2:"Mude-se para o sul. Faça parte.",
 reloc_p:"Recebemos voluntários de todo o lado que querem passar uma temporada no Alentejo ou no Algarve — a dar companhia e a viver o ritmo do sul.",
 reloc_li1:"Apoio a encontrar alojamento na região",reloc_li2:"Integração numa comunidade acolhedora",reloc_li3:"Formação e um Angel experiente nas primeiras visitas",reloc_cta:"Quero mudar-me para ajudar",
 stats_eyebrow:"Confiança",stats_h2:"Uma rede em que pode confiar",
 stat1:"idosos acompanhados",stat2:"Anjos voluntários",stat3:"horas de companhia",stat4:"na solidão sentida",
 vet_note:"Todos os Anjos passam por uma verificação simples — registo criminal e referências — antes das funções com pessoas idosas. É o que protege quem ajudamos, e a si.",
 cta_eyebrow:"Junte-se a nós",cta_h2:"Há uma tarde sua à espera<br>de mudar uma vida.",cta_p:"Comece hoje. A primeira vez é só uma conversa, sem compromisso.",cta_btn:"Tornar-me um Angel",
 foot_tag:"Companhia para quem vive só, no Baixo Alentejo e no Algarve. Uma associação comunitária sem fins lucrativos.",
 foot_h1:"Plataforma",foot_h2:"Regiões",foot_h3:"Também no telemóvel",foot_app:"App para voluntários ↗",foot_rights:"© 2026 Community Angels Association · Alentejo &amp; Algarve",
 m_needs:"O que %s precisa",m_note:"Escolha uma necessidade. Falamos consigo, fazemos a verificação e apresentamo-lo a %s.",need_btn:"Quero ajudar",
 alert:"Obrigado! Vamos pô-lo em contacto para ajudar %1 com: %2.",
 nl_companhia_tarde:"Companhia à tarde",nl_ler:"Ajuda a ler cartas e receitas",nl_boleia_saude:"Boleia ao centro de saúde",nl_conversa:"Conversa no caminho",nl_mercado:"Companhia no mercado",nl_convivios:"Vir aos convívios",nl_passeios:"Passeios acompanhados",nl_chamadas:"Chamadas de companhia",nl_recados:"Boleia a recados",nl_lanches:"Vir aos lanches-convívio",nl_tardes:"Tardes de conversa",
 nc_pw1:"1× por semana",nc_pm1:"1× por mês",nc_pm2:"2× por mês",nc_pw2:"2× por semana",nc_weekly:"semanal",nc_need:"quando precisa",nc_can:"quando puder",
 opp_1:"Tardes de conversa com a Dona Amélia",opp_2:"Acompanhar o Sr. Joaquim à consulta",opp_3:"Lanche-convívio de fim de tarde",opp_4:"Companhia no mercado semanal",opp_5:"Chamadas de boa-disposição",opp_6:"Mãos amigas nos bastidores",opp_7:"Passeios à beira-rio com a Dona Iva",opp_8:"Boleia ao mercado de Loulé",opp_9:"Café e jogos no centro de dia",
 sen_1:"Foi costureira a vida toda. Vive só desde que enviuvou e adora falar do tempo em que cosia para a vila.",sen_2:"Antigo trabalhador rural. Os filhos emigraram e tem dificuldade em chegar às consultas sozinho.",sen_3:"O mercado de sexta é o seu programa da semana, mas já não consegue carregar os sacos sozinha.",sen_4:"Gosta de passear à beira-rio ao fim da tarde, mas tem medo de cair se for sozinha.",sen_5:"Quase sem família por perto. Passa dias inteiros sem falar com ninguém.",sen_6:"Cheia de histórias e de vontade de conviver — só lhe falta companhia para sair de casa."
},
en:{
 nav_people:"The people",nav_opps:"Opportunities",nav_match:"Match",nav_move:"Relocate",nav_how:"How it works",nav_cta:"I want to help",
 hero_eyebrow:"Baixo Alentejo &amp; Algarve",
 hero_h1:"Find who needs you.<br><span class='hl'>In minutes.</span>",
 hero_lead:"The platform that connects volunteers with older people living alone, in the south of Portugal. Browse the board, meet the people, or let smart matching find the right connection.",
 hero_cta1:"Find my match",hero_cta2:"See opportunities",
 trust1:"Free",trust2:"Vetted volunteers",trust3:"1h a week is enough",
 mock_search:"Search near you…",mock_c1_t:"Afternoon chats · Beja",mock_c1_m:"Tuesdays · 15:00",mock_c2_t:"Ride to the doctor · Serpa",mock_c2_m:"Thursday · 9:30",
 mock_ai_b:"Smart match",mock_ai_s:"3 perfect matches for you",mock_float_s:"wants company · Beja",
 strip_partner:"In partnership with",
 match_eyebrow:"Smart match",match_h2:"Tell us how you'd like to help. We'll find who needs you.",
 match_sub:"Answer three questions and we'll match your area, availability and what you enjoy with someone who needs company near you.",
 match_q1:"1 · Where are you?",match_q2:"2 · When are you free?",match_q3:"3 · What do you enjoy?",
 z_remoto:"Remote",z_any:"No preference",q_manha:"Mornings",q_tarde:"Afternoons",q_fds:"Weekends",q_flex:"Flexible",
 g_companhia:"Chatting",g_boleia:"Driving",g_evento:"Hosting gatherings",g_apoio:"Helping with tasks",g_admin:"Behind the scenes",
 match_btn:"Find my match",match_note:"Smart search · conversational AI coming soon",
 why_pre:"Matches your",why_zone:"area",why_like:"interests",why_avail:"availability",why_def:"A great first opportunity",
 people_eyebrow:"The people",people_h2:"Meet who's waiting for you",
 people_lead:"They're not tasks — they're people. See who lives alone, learn their needs, and choose how you'd like to help.",
 pf_all:"All",pf_want:"Want company",pf_ride:"Need a ride",
 people_note:"Profiles are shared with consent and protected — full details are only visible after your verification.",
 plink:"See what they need →",angel_one:"1 Angel already helping",angel_many:"%n Angels already helping",angel_none:"No Angel yet",
 board_eyebrow:"Or by task",board_h2:"The opportunity board",board_lead:"Each card is an afternoon in someone's life. Filter by cause, area or availability.",
 f_remoto:"Remote",count_word:"opportunities",tag_vet:"Requires vetting",spot_one:"spot",spot_many:"spots",filled:"Filled",
 c_companhia:"Companionship",c_boleia:"Ride",c_evento:"Gathering",c_apoio:"Support",c_admin:"Behind the scenes",
 cad_weekly:"Every week",cad_fortnightly:"Fortnightly",cad_one_morning:"One morning",cad_your_pace:"At your pace",
 d_tue:"Tuesdays",d_thu:"Thursday",d_sat:"Saturday",d_wed:"Wednesdays",d_fri:"Fridays",d_flex:"Flexible",
 how_eyebrow:"Simple",how_h2:"How it works",
 step1_t:"1 · Choose",step1_p:"Find an opportunity or a person on the board, or let the match suggest the right connection.",
 step2_t:"2 · Meet",step2_p:"We talk with you, run a simple vetting, and introduce you to the person — only with your yes.",
 step3_t:"3 · Show up",step3_p:"You arrive at the agreed time, bring company and log the visit. One hour a week changes everything.",
 reloc_eyebrow:"Come live and help",reloc_h2:"Move south. Be part of it.",
 reloc_p:"We welcome volunteers from everywhere who want to spend a season in the Alentejo or the Algarve — bringing company and living the rhythm of the south.",
 reloc_li1:"Support finding accommodation in the region",reloc_li2:"Integration into a warm community",reloc_li3:"Training and an experienced Angel on your first visits",reloc_cta:"I want to move and help",
 stats_eyebrow:"Trust",stats_h2:"A network you can trust",
 stat1:"seniors supported",stat2:"volunteer Angels",stat3:"hours of company",stat4:"in felt loneliness",
 vet_note:"Every Angel goes through a simple check — criminal record and references — before roles with older people. It's what protects those we help, and you.",
 cta_eyebrow:"Join us",cta_h2:"An afternoon of yours<br>could change a life.",cta_p:"Start today. The first time is just a conversation, no commitment.",cta_btn:"Become an Angel",
 foot_tag:"Company for those who live alone, in the Baixo Alentejo and the Algarve. A non-profit community association.",
 foot_h1:"Platform",foot_h2:"Regions",foot_h3:"Also on mobile",foot_app:"Volunteer app ↗",foot_rights:"© 2026 Community Angels Association · Alentejo &amp; Algarve",
 m_needs:"What %s needs",m_note:"Choose a need. We talk with you, run the vetting, and introduce you to %s.",need_btn:"I want to help",
 alert:"Thank you! We'll get in touch to help you support %1 with: %2.",
 nl_companhia_tarde:"Afternoon company",nl_ler:"Help reading letters & prescriptions",nl_boleia_saude:"Ride to the health centre",nl_conversa:"A chat along the way",nl_mercado:"Company at the market",nl_convivios:"Coming to gatherings",nl_passeios:"Accompanied walks",nl_chamadas:"Companionship calls",nl_recados:"Rides for errands",nl_lanches:"Coming to the socials",nl_tardes:"Afternoon chats",
 nc_pw1:"1×/week",nc_pm1:"1×/month",nc_pm2:"2×/month",nc_pw2:"2×/week",nc_weekly:"weekly",nc_need:"when needed",nc_can:"whenever you can",
 opp_1:"Afternoon chats with Dona Amélia",opp_2:"Take Mr. Joaquim to his appointment",opp_3:"Late-afternoon social",opp_4:"Company at the weekly market",opp_5:"Friendly check-in calls",opp_6:"Helping hands behind the scenes",opp_7:"Riverside walks with Dona Iva",opp_8:"Ride to the Loulé market",opp_9:"Coffee and games at the day centre",
 sen_1:"She was a seamstress all her life. She's lived alone since she was widowed and loves talking about when she sewed for the town.",sen_2:"A former farm worker. His children emigrated and he struggles to get to appointments on his own.",sen_3:"Friday's market is the highlight of her week, but she can no longer carry the bags alone.",sen_4:"She loves a riverside walk at the end of the day, but is afraid of falling if she goes alone.",sen_5:"Almost no family nearby. He goes whole days without speaking to anyone.",sen_6:"Full of stories and eager to socialise — she just needs company to leave the house."
},
de:{
 nav_people:"Die Menschen",nav_opps:"Angebote",nav_match:"Match",nav_move:"Umziehen",nav_how:"So funktioniert's",nav_cta:"Ich möchte helfen",
 hero_eyebrow:"Baixo Alentejo &amp; Algarve",
 hero_h1:"Finden Sie, wer Sie braucht.<br><span class='hl'>In Minuten.</span>",
 hero_lead:"Die Plattform, die Freiwillige mit allein lebenden älteren Menschen im Süden Portugals verbindet. Durchstöbern Sie die Übersicht, lernen Sie die Menschen kennen, oder lassen Sie das intelligente Match die richtige Verbindung finden.",
 hero_cta1:"Mein Match finden",hero_cta2:"Angebote ansehen",
 trust1:"Kostenlos",trust2:"Geprüfte Freiwillige",trust3:"1 Std./Woche genügt",
 mock_search:"In Ihrer Nähe suchen…",mock_c1_t:"Gespräche am Nachmittag · Beja",mock_c1_m:"Dienstags · 15:00",mock_c2_t:"Fahrt zum Arzt · Serpa",mock_c2_m:"Donnerstag · 9:30",
 mock_ai_b:"Intelligentes Match",mock_ai_s:"3 perfekte Verbindungen für Sie",mock_float_s:"sucht Gesellschaft · Beja",
 strip_partner:"In Partnerschaft mit",
 match_eyebrow:"Intelligentes Match",match_h2:"Sagen Sie uns, wie Sie helfen möchten. Wir finden, wer Sie braucht.",
 match_sub:"Beantworten Sie drei Fragen und wir gleichen Region, Verfügbarkeit und Vorlieben mit jemandem ab, der in Ihrer Nähe Gesellschaft braucht.",
 match_q1:"1 · Wo sind Sie?",match_q2:"2 · Wann haben Sie Zeit?",match_q3:"3 · Was machen Sie gern?",
 z_remoto:"Aus der Ferne",z_any:"Egal",q_manha:"Vormittags",q_tarde:"Nachmittags",q_fds:"Wochenenden",q_flex:"Flexibel",
 g_companhia:"Plaudern",g_boleia:"Fahren",g_evento:"Treffen begleiten",g_apoio:"Bei Aufgaben helfen",g_admin:"Hinter den Kulissen",
 match_btn:"Mein Match finden",match_note:"Intelligente Suche · bald mit Konversations-KI",
 why_pre:"Passt zu",why_zone:"Ihrer Region",why_like:"Ihren Vorlieben",why_avail:"Ihrer Verfügbarkeit",why_def:"Eine gute erste Gelegenheit",
 people_eyebrow:"Die Menschen",people_h2:"Lernen Sie kennen, wer auf Sie wartet",
 people_lead:"Es sind keine Aufgaben — es sind Menschen. Sehen Sie, wer allein lebt, lernen Sie ihre Bedürfnisse kennen und wählen Sie, wie Sie helfen möchten.",
 pf_all:"Alle",pf_want:"Suchen Gesellschaft",pf_ride:"Brauchen eine Fahrt",
 people_note:"Profile werden mit Einwilligung geteilt und geschützt — vollständige Daten sind erst nach Ihrer Prüfung sichtbar.",
 plink:"Sehen, was sie brauchen →",angel_one:"1 Engel hilft bereits",angel_many:"%n Engel helfen bereits",angel_none:"Noch kein Engel",
 board_eyebrow:"Oder nach Aufgabe",board_h2:"Die Angebotsübersicht",board_lead:"Jede Karte ist ein Nachmittag im Leben eines Menschen. Filtern Sie nach Bereich, Region oder Verfügbarkeit.",
 f_remoto:"Aus der Ferne",count_word:"Angebote",tag_vet:"Prüfung erforderlich",spot_one:"Platz",spot_many:"Plätze",filled:"Belegt",
 c_companhia:"Gesellschaft",c_boleia:"Fahrt",c_evento:"Treffen",c_apoio:"Unterstützung",c_admin:"Hinter den Kulissen",
 cad_weekly:"Jede Woche",cad_fortnightly:"Alle zwei Wochen",cad_one_morning:"Ein Vormittag",cad_your_pace:"In Ihrem Tempo",
 d_tue:"Dienstags",d_thu:"Donnerstag",d_sat:"Samstag",d_wed:"Mittwochs",d_fri:"Freitags",d_flex:"Flexibel",
 how_eyebrow:"Einfach",how_h2:"So funktioniert's",
 step1_t:"1 · Wählen",step1_p:"Finden Sie ein Angebot oder eine Person in der Übersicht, oder lassen Sie das Match die richtige Verbindung vorschlagen.",
 step2_t:"2 · Kennenlernen",step2_p:"Wir sprechen mit Ihnen, führen eine einfache Prüfung durch und stellen Sie der Person vor — nur mit Ihrem Ja.",
 step3_t:"3 · Erscheinen",step3_p:"Sie kommen zur vereinbarten Zeit, leisten Gesellschaft und erfassen den Besuch. Eine Stunde pro Woche verändert alles.",
 reloc_eyebrow:"Kommen, leben, helfen",reloc_h2:"Ziehen Sie in den Süden. Machen Sie mit.",
 reloc_p:"Wir empfangen Freiwillige aus aller Welt, die eine Zeit im Alentejo oder in der Algarve verbringen möchten — Gesellschaft schenken und den Rhythmus des Südens leben.",
 reloc_li1:"Unterstützung bei der Unterkunftssuche in der Region",reloc_li2:"Integration in eine herzliche Gemeinschaft",reloc_li3:"Schulung und ein erfahrener Engel bei den ersten Besuchen",reloc_cta:"Ich möchte umziehen und helfen",
 stats_eyebrow:"Vertrauen",stats_h2:"Ein Netzwerk, dem Sie vertrauen können",
 stat1:"begleitete Senioren",stat2:"freiwillige Engel",stat3:"Stunden Gesellschaft",stat4:"weniger empfundene Einsamkeit",
 vet_note:"Jeder Engel durchläuft eine einfache Prüfung — Führungszeugnis und Referenzen — vor Tätigkeiten mit älteren Menschen. Das schützt die, denen wir helfen, und Sie.",
 cta_eyebrow:"Machen Sie mit",cta_h2:"Ein Nachmittag von Ihnen<br>kann ein Leben verändern.",cta_p:"Beginnen Sie heute. Das erste Mal ist nur ein Gespräch, ohne Verpflichtung.",cta_btn:"Engel werden",
 foot_tag:"Gesellschaft für alle, die allein leben, im Baixo Alentejo und in der Algarve. Ein gemeinnütziger Gemeinschaftsverein.",
 foot_h1:"Plattform",foot_h2:"Regionen",foot_h3:"Auch mobil",foot_app:"Freiwilligen-App ↗",foot_rights:"© 2026 Community Angels Association · Alentejo &amp; Algarve",
 m_needs:"Was %s braucht",m_note:"Wählen Sie ein Bedürfnis. Wir sprechen mit Ihnen, führen die Prüfung durch und stellen Sie %s vor.",need_btn:"Ich möchte helfen",
 alert:"Danke! Wir melden uns, um Ihnen zu helfen, %1 zu unterstützen mit: %2.",
 nl_companhia_tarde:"Gesellschaft am Nachmittag",nl_ler:"Hilfe beim Lesen von Briefen & Rezepten",nl_boleia_saude:"Fahrt zum Gesundheitszentrum",nl_conversa:"Gespräch unterwegs",nl_mercado:"Begleitung auf dem Markt",nl_convivios:"Zu Treffen kommen",nl_passeios:"Begleitete Spaziergänge",nl_chamadas:"Gesellschafts-Anrufe",nl_recados:"Fahrten für Besorgungen",nl_lanches:"Zu den Imbiss-Treffen kommen",nl_tardes:"Nachmittagsgespräche",
 nc_pw1:"1×/Woche",nc_pm1:"1×/Monat",nc_pm2:"2×/Monat",nc_pw2:"2×/Woche",nc_weekly:"wöchentlich",nc_need:"bei Bedarf",nc_can:"wann immer möglich",
 opp_1:"Nachmittagsgespräche mit Dona Amélia",opp_2:"Herrn Joaquim zum Arzttermin begleiten",opp_3:"Geselliger Nachmittagsimbiss",opp_4:"Begleitung auf dem Wochenmarkt",opp_5:"Aufmunternde Anrufe",opp_6:"Helfende Hände hinter den Kulissen",opp_7:"Spaziergänge am Fluss mit Dona Iva",opp_8:"Fahrt zum Markt in Loulé",opp_9:"Kaffee und Spiele im Tageszentrum",
 sen_1:"Sie war ihr Leben lang Näherin. Seit dem Tod ihres Mannes lebt sie allein und erzählt gern von der Zeit, als sie für den Ort nähte.",sen_2:"Ehemaliger Landarbeiter. Seine Kinder sind ausgewandert und er kommt allein nur schwer zu Terminen.",sen_3:"Der Freitagsmarkt ist ihr Höhepunkt der Woche, aber die Taschen kann sie nicht mehr allein tragen.",sen_4:"Sie geht am Abend gern am Fluss spazieren, hat aber Angst zu stürzen, wenn sie allein geht.",sen_5:"Kaum Familie in der Nähe. Tagelang spricht er mit niemandem.",sen_6:"Voller Geschichten und Lust auf Gesellschaft — ihr fehlt nur Begleitung, um aus dem Haus zu gehen."
},
fr:{
 nav_people:"Les personnes",nav_opps:"Missions",nav_match:"Match",nav_move:"S'installer",nav_how:"Comment ça marche",nav_cta:"Je veux aider",
 hero_eyebrow:"Baixo Alentejo &amp; Algarve",
 hero_h1:"Trouvez qui a besoin de vous.<br><span class='hl'>En quelques minutes.</span>",
 hero_lead:"La plateforme qui relie les bénévoles aux personnes âgées vivant seules, dans le sud du Portugal. Parcourez le tableau, rencontrez les personnes, ou laissez le match intelligent trouver la bonne connexion.",
 hero_cta1:"Trouver mon match",hero_cta2:"Voir les missions",
 trust1:"Gratuit",trust2:"Bénévoles vérifiés",trust3:"1h par semaine suffit",
 mock_search:"Rechercher près de vous…",mock_c1_t:"Après-midis de conversation · Beja",mock_c1_m:"Mardis · 15:00",mock_c2_t:"Trajet chez le médecin · Serpa",mock_c2_m:"Jeudi · 9:30",
 mock_ai_b:"Match intelligent",mock_ai_s:"3 connexions parfaites pour vous",mock_float_s:"cherche de la compagnie · Beja",
 strip_partner:"En partenariat avec",
 match_eyebrow:"Match intelligent",match_h2:"Dites-nous comment vous aimeriez aider. Nous trouvons qui a besoin de vous.",
 match_sub:"Répondez à trois questions et nous croisons votre région, vos disponibilités et vos envies avec quelqu'un qui a besoin de compagnie près de chez vous.",
 match_q1:"1 · Où êtes-vous ?",match_q2:"2 · Quand êtes-vous disponible ?",match_q3:"3 · Qu'aimez-vous faire ?",
 z_remoto:"À distance",z_any:"Peu importe",q_manha:"Matins",q_tarde:"Après-midis",q_fds:"Week-ends",q_flex:"Flexible",
 g_companhia:"Discuter",g_boleia:"Conduire",g_evento:"Animer des rencontres",g_apoio:"Aider aux tâches",g_admin:"En coulisses",
 match_btn:"Trouver mon match",match_note:"Recherche intelligente · IA conversationnelle bientôt",
 why_pre:"Correspond à",why_zone:"votre région",why_like:"vos envies",why_avail:"vos disponibilités",why_def:"Une belle première mission",
 people_eyebrow:"Les personnes",people_h2:"Rencontrez ceux qui vous attendent",
 people_lead:"Ce ne sont pas des tâches — ce sont des personnes. Voyez qui vit seul, découvrez leurs besoins, et choisissez comment aider.",
 pf_all:"Tout",pf_want:"Cherchent de la compagnie",pf_ride:"Besoin d'un trajet",
 people_note:"Profils partagés avec consentement et protégés — les données complètes ne sont visibles qu'après votre vérification.",
 plink:"Voir ce dont ils ont besoin →",angel_one:"1 Ange aide déjà",angel_many:"%n Anges aident déjà",angel_none:"Pas encore d'Ange",
 board_eyebrow:"Ou par mission",board_h2:"Le tableau des missions",board_lead:"Chaque carte est un après-midi dans la vie de quelqu'un. Filtrez par cause, région ou disponibilité.",
 f_remoto:"À distance",count_word:"missions",tag_vet:"Vérification requise",spot_one:"place",spot_many:"places",filled:"Complet",
 c_companhia:"Compagnie",c_boleia:"Trajet",c_evento:"Rencontre",c_apoio:"Aide",c_admin:"En coulisses",
 cad_weekly:"Chaque semaine",cad_fortnightly:"Tous les 15 jours",cad_one_morning:"Une matinée",cad_your_pace:"À votre rythme",
 d_tue:"Mardis",d_thu:"Jeudi",d_sat:"Samedi",d_wed:"Mercredis",d_fri:"Vendredis",d_flex:"Flexible",
 how_eyebrow:"Simple",how_h2:"Comment ça marche",
 step1_t:"1 · Choisissez",step1_p:"Trouvez une mission ou une personne sur le tableau, ou laissez le match suggérer la bonne connexion.",
 step2_t:"2 · Rencontrez",step2_p:"Nous échangeons avec vous, faisons une vérification simple et vous présentons à la personne — uniquement avec votre accord.",
 step3_t:"3 · Présentez-vous",step3_p:"Vous venez à l'heure convenue, apportez de la compagnie et enregistrez la visite. Une heure par semaine change tout.",
 reloc_eyebrow:"Venez vivre et aider",reloc_h2:"Installez-vous au sud. Faites-en partie.",
 reloc_p:"Nous accueillons des bénévoles du monde entier qui veulent passer une saison dans l'Alentejo ou en Algarve — apporter de la compagnie et vivre au rythme du sud.",
 reloc_li1:"Aide pour trouver un logement dans la région",reloc_li2:"Intégration dans une communauté chaleureuse",reloc_li3:"Formation et un Ange expérimenté lors des premières visites",reloc_cta:"Je veux m'installer pour aider",
 stats_eyebrow:"Confiance",stats_h2:"Un réseau de confiance",
 stat1:"aînés accompagnés",stat2:"Anges bénévoles",stat3:"heures de compagnie",stat4:"de solitude ressentie",
 vet_note:"Chaque Ange passe une vérification simple — casier judiciaire et références — avant les missions auprès des personnes âgées. C'est ce qui protège ceux que nous aidons, et vous.",
 cta_eyebrow:"Rejoignez-nous",cta_h2:"Un de vos après-midis<br>peut changer une vie.",cta_p:"Commencez aujourd'hui. La première fois, c'est juste une conversation, sans engagement.",cta_btn:"Devenir un Ange",
 foot_tag:"De la compagnie pour ceux qui vivent seuls, dans le Baixo Alentejo et l'Algarve. Une association communautaire à but non lucratif.",
 foot_h1:"Plateforme",foot_h2:"Régions",foot_h3:"Aussi sur mobile",foot_app:"App bénévoles ↗",foot_rights:"© 2026 Community Angels Association · Alentejo &amp; Algarve",
 m_needs:"Ce dont %s a besoin",m_note:"Choisissez un besoin. Nous échangeons avec vous, faisons la vérification et vous présentons à %s.",need_btn:"Je veux aider",
 alert:"Merci ! Nous vous recontacterons pour aider %1 avec : %2.",
 nl_companhia_tarde:"Compagnie l'après-midi",nl_ler:"Aide à lire courriers & ordonnances",nl_boleia_saude:"Trajet au centre de santé",nl_conversa:"Discussion en chemin",nl_mercado:"Compagnie au marché",nl_convivios:"Venir aux rencontres",nl_passeios:"Promenades accompagnées",nl_chamadas:"Appels de compagnie",nl_recados:"Trajets pour courses",nl_lanches:"Venir aux goûters conviviaux",nl_tardes:"Après-midis de conversation",
 nc_pw1:"1×/semaine",nc_pm1:"1×/mois",nc_pm2:"2×/mois",nc_pw2:"2×/semaine",nc_weekly:"hebdomadaire",nc_need:"au besoin",nc_can:"quand vous pouvez",
 opp_1:"Après-midis de conversation avec Dona Amélia",opp_2:"Accompagner M. Joaquim à son rendez-vous",opp_3:"Goûter convivial en fin de journée",opp_4:"Compagnie au marché hebdomadaire",opp_5:"Appels de bonne humeur",opp_6:"Un coup de main en coulisses",opp_7:"Promenades au bord de l'eau avec Dona Iva",opp_8:"Trajet au marché de Loulé",opp_9:"Café et jeux au centre de jour",
 sen_1:"Elle a été couturière toute sa vie. Veuve, elle vit seule et adore parler du temps où elle cousait pour le village.",sen_2:"Ancien ouvrier agricole. Ses enfants ont émigré et il a du mal à se rendre seul à ses rendez-vous.",sen_3:"Le marché du vendredi est son moment de la semaine, mais elle ne peut plus porter les sacs seule.",sen_4:"Elle aime se promener au bord de l'eau en fin de journée, mais a peur de tomber si elle y va seule.",sen_5:"Presque pas de famille à proximité. Il passe des journées entières sans parler à personne.",sen_6:"Pleine d'histoires et d'envie de sortir — il ne lui manque que de la compagnie pour quitter la maison."
}
};
